### ISSUE TITLE
Storybook: Quiz Answers Component

### ISSUE THREAD

**Issue by dpfernandes** [HackYourFuture-CPH/Guide-IT#10]
## User story

**Who:** **As a** developer
**What:** **I want to** be have a quiz answer component that can have different options (2 or 3) in form of a Radio Button.
**Why:** **so that I can** that can be the same component in multiple pages/questions.

## Acceptance criteria

Create a storybook for the Quiz Answers that meets what's illustrated below:

<img width="499" alt="Screenshot 2021-04-13 at 01 43 16" src="https://user-images.githubusercontent.com/6642037/114476006-be7da780-9bf9-11eb-9f1d-e57f6cf33a67.png">
<img width="527" alt="Screenshot 2021-04-13 at 01 43 08" src="https://user-images.githubusercontent.com/6642037/114476020-c2a9c500-9bf9-11eb-8045-b1658addb036.png">

Check the wireframes here: https://www.figma.com/file/9SJRaxPSuPI3lSl8ULNyJ8/GuideIT-For-Developers?node-id=0%3A1

## Implementation details

Use **Knobs** where we can choose  **Text** for the answers,  **Type**, 2 options or 3 levels of agreement/disagreement
For the text use  [Roboto+Mono](https://fonts.google.com/specimen/Roboto+Mono?preview.text=What%20is%20GuideIT%3F&preview.text_type=custom) and color #298F8A

**Comment by cph-kiwi** [comment]
This issue has already been address in issue #12 - PR #49. We have some duplication happening
