### ISSUE TITLE
Storybook: Career Quiz Result Page Component

### ISSUE THREAD

**Issue by dpfernandes** [HackYourFuture-CPH/Guide-IT#19]
## User story

**Who:** **As a** user
**What:** **I want to** be open the Career Quiz Result Page
**Why:** **so that I can** see the results of the QUIZ.

## Acceptance criteria

Create a storybook component for the Career Quiz Result Page where we aggregate all the components below:

- Robot logo and a label below with the text BASED ON QUIZ RESULTS
- HEADER - https://github.com/HackYourFuture-CPH/Guide-IT/issues/13
- CARD for YOUR PERSONAL PROFILE - https://github.com/HackYourFuture-CPH/Guide-IT/issues/16
- CARD for YOUR PROFESSIONAL PROFILE - https://github.com/HackYourFuture-CPH/Guide-IT/issues/16
- TEASER - https://github.com/HackYourFuture-CPH/Guide-IT/issues/17
- BUTTON - https://github.com/HackYourFuture-CPH/Guide-IT/issues/18

 
These are the 3 different options for the career quiz result page can look like

<img width="545" alt="Screenshot 2021-04-13 at 15 37 38" src="https://user-images.githubusercontent.com/6642037/114561956-587f3780-9c6e-11eb-920b-5f5121ee93e4.png">
<img width="545" alt="Screenshot 2021-04-13 at 15 37 28" src="https://user-images.githubusercontent.com/6642037/114561976-5cab5500-9c6e-11eb-968e-3855bc3b32c0.png">
<img width="545" alt="Screenshot 2021-04-13 at 15 37 17" src="https://user-images.githubusercontent.com/6642037/114561985-5f0daf00-9c6e-11eb-8a97-22f76ea98331.png">

Check the wireframes here: https://www.figma.com/file/9SJRaxPSuPI3lSl8ULNyJ8/GuideIT-For-Developers?node-id=0%3A1

## Implementation details

Use the image Vector.svg located in this folder **/src/client/assets/images/** as a background image and find a way for half of the it to have a layer of opacity like we can see in the screenshot above.

**Comment by cph-kiwi** [comment]
@dpfernandes which dummy page in containers should we use as our starting point? We want to avoid duplication where possible.

**Comment by JyothiNandyala** [comment]
Hi Aijaz i have run your storybook in that i saw like 'your professional profile is going out of the page and also that card ,could you please check.
