### ISSUE TITLE
Storybook: Card Job title Summary Component

### ISSUE THREAD

**Issue by dpfernandes** [HackYourFuture-CPH/Guide-IT#20]
## User story

**Who:** **As a** user
**What:** **I want to** be able to see different job results depending on the answers that I give in the quiz
**Why:** **so that I can** see more info about the job title.

## Acceptance criteria

Create a storybook for the **Card** Job title Summary Component that meets what's illustrated below and highlighted in pink

<img width="550" alt="Screenshot 2021-04-13 at 16 40 20" src="https://user-images.githubusercontent.com/6642037/114573563-c4669d80-9c78-11eb-91c1-8057fc9c0fa3.png">
<img width="550" alt="Screenshot 2021-04-13 at 16 55 57" src="https://user-images.githubusercontent.com/6642037/114574118-422aa900-9c79-11eb-86f2-6ce3c2df0311.png">
<img width="550" alt="Screenshot 2021-04-13 at 16 56 22" src="https://user-images.githubusercontent.com/6642037/114574097-3ccd5e80-9c79-11eb-8dd8-0d29f48bb2ac.png">

## Implementation details

Implement knobs so that we can change the title(job title) and content of the card.

Use the font [Roboto+Mono](https://fonts.google.com/specimen/Roboto+Mono?preview.text=What%20is%20GuideIT%3F&preview.text_type=custom) and the color #000000 for the title and for the bullet points use. Make sure that the bullet points are in an area with this color #F0F0F0.

**Comment by JyothiNandyala** [comment]
Hi enqira its looking good.
